### ISSUE TITLE
Testing Scroll Wheel

### ISSUE THREAD

**Issue by lsizemore8** [BryanGraeser/fallen-flame#14]
Checking the scroll wheel amount was done in a slightly strange way, so this'll have to be tested when everything is set up

**Comment by foxhatleo** [comment]
I have added a temp alternative in light-controller branch that uses comma and period as an alternative to scroll wheel because a) this needs to work to test player light, and b) I don't have a mouse at the moment, just my touchpad. Maybe we can talk about preserving this alternative or some alternative way for people who don't have a mouse wheel?

**Comment by lsizemore8** [comment]
I'm okay with keeping it as an alternative, but that is a discussion for everyone. I think I just figured out how to get the scrolling working without making a real weird architecture choice, so that should be fixed in a tad, so we should be able to have both.
