### ISSUE TITLE
Resetting level seems to reuse controller instances

### ISSUE THREAD

**Issue by foxhatleo** [BryanGraeser/fallen-flame#24]
Currently, pressing R (reset) will cause a fatal error in LightController. This is because when GameEngine resets the game, it does not re-create a new LevelController instance--instead if simply call dispose() on it and then populate(). LevelController then calls initialize() on a LightController instance that is already initialised.

My understanding is that when a controller instance is disposed it can no longer be used in any way (a new LevelController instance should be created when resetting a level). The LightController I wrote does not allow being initialized twice.

What do we think of this? I'm not too sure about what practice we want to follow.

**Comment by lsizemore8** [comment]
Is there a way to check if the LightController is initialized already or not, and only initialize if it's not? Is that even possible? 

Otherwise, it sounds like it's best to change how GameEngine resets the LevelController, so we only allow one LevelController and update all of the values from the JSON.

**Comment by BryanGraeser** [comment]
You could just recreate LevelController after calling dispose

**Comment by foxhatleo** [comment]
I have refactored light controller that it will allow being re-initialised/re-populated as Laura brings up a good point about objects are expensive to create, so this should not be a problem anymore.
